Update colour convars to use RGBA format
momentum-mod/docs pull request #175
Opened 2021-02-12 21:11 UTC by braem

Closes https://github.com/momentum-mod/docs/issues/171

To be merged when 0.8.8 releases to playtesters.

2021-02-14 00:48 UTC, Gocnak requested changes

2021-02-14 00:48 UTC, Gocnak commented on _posts/convars/2020-04-30-cl_crosshair_color.md
> +Set the crosshair's color. Accepts hex color value in format RGBA. If RGB is supplied, alpha is set to 255.
Not necessarily a hex color anymore.

2021-02-14 00:48 UTC, Gocnak commented on _posts/convars/2020-04-30-mom_ghost_color.md
> +The color & alpha of the player's ghost. Accepts hex color value in format RGBA. If RGB is supplied, the alpha is set to 255.
Same here, no longer a hex color.

2021-02-14 06:51 UTC, braem commented on _posts/convars/2020-04-30-cl_crosshair_color.md
> +Set the crosshair's color. Accepts hex color value in format RGBA. If RGB is supplied, alpha is set to 255.
woops!

2021-04-15 03:46 UTC, Gocnak approved these changes

2021-04-15 03:46 UTC, merged