Create trigger_bounce_stickybomb doc page
momentum-mod/docs pull request #217
Opened 2021-09-26 07:52 UTC by hexaflexahexagon

closes https://github.com/momentum-mod/docs/issues/208

2021-09-26 16:00 UTC, braem requested changes

2021-09-26 16:00 UTC, braem commented on _posts/entities/2021-09-26-trigger_bounce_stickybomb.md
> +title: trigger_bounce_stickybomb
it is `trigger_bounce_stickybombs` (plural)

2021-09-28 00:45 UTC, hexaflexahexagon commented
i should probably slow down when doing documentation... at least i got the branch name right lol

2021-09-29 08:25 UTC, braem approved these changes

2021-09-29 08:25 UTC, braem commented
naw is what reviews are for ^^

2021-09-29 08:27 UTC, merged