feat: ranking points and cosmetic xp docpage
momentum-mod/docs pull request #257
Opened 2022-02-01 18:59 UTC by antjlo

refer to #255

2022-02-02 00:01 UTC, antjlo commented
Was trying to rename it from feat to docs but I suck at git apparently

2022-02-02 16:52 UTC, antjlo commented
You can merge it now I renamed it

2022-02-07 19:31 UTC, Gocnak commented on _posts/guides/2022-2-1-guide_ranking-cosmetic-xp.md
> +  - exp
XP can be kept along with the full word. The more tags, the easier the search process, but you don't want exp and XP, for example

2022-02-07 19:35 UTC, braem commented on _posts/guides/2022-2-1-guide_ranking-cosmetic-xp.md
> +  - exp
Figured searching for XP would have experience come up anyhow, but maybe not always yeah. Exp for instance would have both exp and experience show.
Mainly trying to cut down on the clutter of the tags page, there's a lot of tags

2022-02-13 19:05 UTC, antjlo commented
Sorry for the late reply, #git-activity doesn't show this and I haven't had time to check github

2022-02-16 04:14 UTC, braem requested changes
Just a couple more things, mainly that backslashes are being rendered instead of intended newlines

2022-02-16 04:14 UTC, braem commented on _posts/guides/2022-2-1-guide_ranking-cosmetic-xp.md
> +Player sets a time of rank 468 on a map with 1333 completions.\
Note that this renders as
![image](https://user-images.githubusercontent.com/9014762/154193788-7b168575-3e44-490e-9248-4e563b41c36b.png)

Will have to use `<br>` when inside an html tag I believe. There are other instances of this in this guide as well.

2022-02-16 04:14 UTC, braem commented on _posts/guides/2022-2-1-guide_ranking-cosmetic-xp.md
> +The formula to determine group size, A(x) (where x is the # of completions of the map), is\
```suggestion
The formula to determine group size, `A(x)` (where `x` is the # of completions of the map), is\
```

2022-02-17 21:01 UTC, braem requested changes

2022-02-17 21:01 UTC, braem commented on _posts/guides/2022-2-1-guide_ranking-cosmetic-xp.md
> +<sup>_max(A, B) simply returns the value of the larger parameter._\
```suggestion
<sup>_max(A, B) simply returns the value of the larger parameter._<br>
```

2022-02-17 21:01 UTC, braem commented on _posts/guides/2022-2-1-guide_ranking-cosmetic-xp.md
> +<sup>Ex.\
```suggestion
<sup>Ex.<br>
```

2022-02-18 15:14 UTC, antjlo commented
> Feel free to just use github to commit the suggestion - commits will be squashed on merge anyhow

I only realized this yesterday lol, you don't know how long it took for me to realize this

2022-02-21 20:49 UTC, braem approved these changes

2022-02-21 20:56 UTC, braem commented
Good to go - just has to be rebased. Odd as there are no actual conflicts but that merge commit is probably what's killing ya.

You can use `git reset HEAD~6` to go back 6 commits, then commit again, making sure it's just the guide. You would need to then force push (`git push --force`)

2022-02-21 21:02 UTC, merged

2022-02-21 21:03 UTC, braem commented
> Good to go - just has to be rebased. Odd as there are no actual conflicts but that merge commit is probably what's killing ya.
> 
> You can use `git reset HEAD~6` to go back 6 commits, then commit again, making sure it's just the guide. You would need to then force push (`git push --force`)

Nevermind, squash and rebase was smart enough to resolve