Docs: Updated Custom HUD menus with new menu layout
momentum-mod/docs pull request #266
Opened 2022-02-17 00:11 UTC by OstojaOfficial

Closes #226.

2022-02-17 00:22 UTC, bltech requested changes
Only needs a few fixups, much appreciated!

2022-02-17 00:22 UTC, bltech commented on _posts/commands/2020-10-20-chaos_hud_menu_reload.md
> +ccom_ref: chaoshud_menu_show
Typo

2022-02-17 00:22 UTC, bltech commented on _posts/guides/2020-09-05-guide_custom-hud-menus.md
> +Hud menus utilize Valve developed data format known as KeyValues3 (KV3).
Weird sentence structure, try to avoid the repetition

2022-02-17 00:22 UTC, bltech commented on _posts/guides/2020-09-05-guide_custom-hud-menus.md
>  `"1"` refers to the number in the menu the command is at, `"label"` is the text that shows for the button on the menu, and `"command"` is the console command that's inputted into console.
Please go through the other parts of text and make sure they still apply, this block of text for example isn't valid anymore

2022-02-17 00:22 UTC, bltech commented on _posts/guides/2020-09-05-guide_custom-hud-menus.md
>  Hud menus allow a maximum of 9 commands, accessed through numbers 1-9.
This is no longer accurate either, the menu will paginate accordingly when you add more than 9 entries

2022-02-17 00:22 UTC, bltech commented on _posts/commands/2020-10-20-chaos_hud_menu_show.md
>  Parses the `cfg/menu/savelocmenu.vdf` file and shows the hud menu if it isn't already open. If it is open already, hides it.
File ending needs to be changed to kv3

2022-02-17 00:22 UTC, bltech commented on _posts/commands/2020-10-20-chaos_hud_menu_show.md
>  Parses the `cfg/menu/rulermenu.vdf` file and shows the hud menu if it isn't already open. If it is open already, hides it.
Same

2022-02-17 00:22 UTC, bltech commented on _posts/guides/2020-09-05-guide_custom-hud-menus.md
>  The parameter for this command will autofill with all the available hud menus.
Line 29 is also no longer accurate (bless github for not allowing me to comment on unchanged lines)

2022-02-17 01:21 UTC, OstojaOfficial commented
> Only needs a few fixups, much appreciated!

Everything should be fixed now.

2022-02-17 21:17 UTC, braem approved these changes

2022-02-21 20:58 UTC, braem approved these changes

2022-02-21 20:59 UTC, merged