Edited "What is surf" and added "How surf works".
momentum-mod/docs pull request #270
Opened 2022-02-22 22:17 UTC by Jedno

2022-02-22 22:44 UTC, tsa96 requested changes
This has some potential but needs a bit of work.

Firstly there's a handful of typos and punctuation errors, I'd suggest running it through a spell checker like on Google Docs at the very least.

2022-02-22 22:44 UTC, tsa96 commented on _posts/guides/2021-12-21-guide_gamemode-info-surf.md
> +Surf is a very popular gamemode that derives from the same source bug as bhop and ahop. Even thought it came from a bug it became one of the most popular minigames on games like cs:s cs:go team fortr
I'm not sure it's right to call surf movement a "bug" (and it's certainly not the same as ahop), it's a product of increasing sv_airaccelerate significantly to give you greater air control, the same as with bhop and I believe most climb variants. I also wouldn't call it a minigame, I think gamemode/sub-game/custom server might be better.

Typo in "Even thought".

Let's try and improve our punctuation a little, "Even thought it came from a bug it became" can be "Even thought it came from a bug, it became" (though as above, I don't think it's right to call it a bug).

The game names should be capitalised.

2022-02-22 22:44 UTC, tsa96 commented on _posts/guides/2021-12-21-guide_gamemode-info-surf.md
> +You can surf by holding A on the right side of the ramp and D on the left without holding W.
Let's change "You can surf" to something like "Surfing on a ramp requries". Comma between "left" and "without".

2022-02-22 22:44 UTC, tsa96 commented on _posts/guides/2021-12-21-guide_gamemode-info-surf.md
> +If you want to jump you need to slowly start looking at the ramp and when you're halfway up look directly at it.
I'm a little confused by this, do you mean when starting a stage? If that's the case let's clarify with by starting with "To begin boarding the ramp by jumping". Though isn't this also the case if you don't jump?

2022-02-22 22:44 UTC, tsa96 commented on _posts/guides/2021-12-21-guide_gamemode-info-surf.md
> +When you are mid-air its beneficial to strafe by looking left while holding A then switcing to looking right while holding D and repeating that.
Typo on "switching". I don't like the "and repeating that", I think you're talking about strafing for speedgame somewhat but that's not necessary, the point should be about always holding the correct strafe key when turning.

2022-02-23 00:27 UTC, antjlo commented
> This has some potential but needs a bit of work.
> 
> Firstly there's a handful of typos and punctuation errors, I'd suggest running it through a spell checker like on Google Docs at the very least.

Easybib and grammarly are free I don't know any others but you can use them in conjuction if you want it as perfect as possible back and fourth, its annoying but i've done it before and it worked

2022-02-24 00:44 UTC, tsa96 commented on _posts/guides/2021-12-21-guide_gamemode-info-surf.md
> +Surf is a very popular gamemode that derives from the same source bug as bhop and ahop. Even thought it came from a bug it became one of the most popular minigames on games like cs:s cs:go team fortr
@Jedno last change is a little better, but please capitalise the game names properly.

Also, lets add a little bit to explain why air control is important, perhaps: _increasing sv_airaccelerate setting, giving better air control thereby allowing the player to perform sharp turns in the air. This also allows the player to "surf" along angled surfaces known as "ramps"._

2022-02-24 00:48 UTC, tsa96 commented on _posts/guides/2021-12-21-guide_gamemode-info-surf.md
> +When you are mid-air its beneficial to strafe by looking left while holding A then switcing to looking right while holding D and repeating that.
Still not too happy with this, still the issue in the latter part of my above comment.

2022-02-24 01:11 UTC, tsa96 commented
Okay I've spoken with the team on this and for this to get merged we'd really need to see something more fleshed out.

Our goal for these pages is to make something that comprehensively explains the mode, including much more detailed descriptions of what the gamemode is and how the mechanics work (a good example is the [ahop section](https://docs.momentum-mod.org/guide/gamemode-ahop/)). I'm afraid this PR feels too small to really even help build off of in that regard. I've been trying to keep with some suggestions in comments here but I think if we are going to build this into something worth merging, we should discuss it more in Discord rather than in Github review.

So: if you wanna to keep working on this then great, but lets move over to Discord and work on it there to try make something more substantial, maybe with input from some others there, I'll be happy to help.

I'm going to close this PR for now, lets work on it some more, and if we can develop this into something more substantial you can open a new one.

2022-02-24 01:11 UTC, closed without merging