feat: Added quake3-to-source-guide and images
momentum-mod/docs pull request #284
Opened 2022-04-10 15:11 UTC by TheNerdMan

Mac couldn't get the local instance to work so I'm here doing this PR and MD files for him. 

Side note: Its so needlessly compliclated to create a doc page for a non developer wtf

2022-04-10 15:31 UTC, hexaflexahexagon commented
You can just use the github web gui for basic pages with no images, I've done a few that way.

2022-04-10 15:56 UTC, braem commented
What's the hard part? Should just need to install ruby & jekyll, clone, bundle, then run jekyll serve.

2022-04-10 19:15 UTC, TheNerdMan commented
I think my comment about the complexity of it is coming from a non dev view point. To install all those things to just get a page up and running. Maybe I'm just being pedantic but @hexaflexahexagon's comment about using github's web GUI is probably a good thing that could maybe be added to the [How to Create a Documentation Page](https://docs.momentum-mod.org/guide/create-docs-page/) for those who need to make edits but don't want to have to go through the local setup

2022-04-13 18:41 UTC, braem requested changes
Well written! Just trying to keep the number of tags low so our https://docs.momentum-mod.org/tags/ page doesnt become a mess.

Also could definitely be utilizing notices more, eg:

```
{:.notice--info}
blah blah blah
```
but looks like this guide will be touched again anyhow for when haste and other things are added.

2022-04-13 18:41 UTC, braem commented on _posts/guides/2022-04-10-guide_porting_quake3-to-source.md
> +  - porting
Some of these tags are redundant
```suggestion
  - mapping
  - porting
```

2022-04-14 07:57 UTC, TheNerdMan commented
> Also could definitely be utilizing notices more
Okie dokie, this is Mac's article so I'll go over it with him to figure out where it would make sense to add the notices. Do you have any suggestions that I can bring up with him?

2022-04-14 08:02 UTC, braem commented
> > Also could definitely be utilizing notices more
> 
> Okie dokie, this is Mac's article so I'll go over it with him to figure out where it would make sense to add the notices. Do you have any suggestions that I can bring up with him?

Fine for now, just in the future it's good to know that we have them (info in blue, warning in yellow, and danger in red) in the case we want to highlight something in particular. They're specific to jekyll's markdown iirc (kramdown?) so it's hard to preview it without a working setup though.

2022-04-14 08:05 UTC, braem approved these changes

2022-04-14 08:05 UTC, merged