Add Localization guide
momentum-mod/docs pull request #302
Opened 2022-10-12 08:03 UTC by Gocnak

2022-10-12 08:59 UTC, tsa96 requested changes
This is great, thanks for doing this. It all reads correctly, only suggestion I have is adding some more convenient env var handling tips

2022-10-12 08:59 UTC, tsa96 commented on _posts/guides/2022-10-11-guide_localization.md
> +On Windows (PowerShell):
I find it's most convenient to add this to environment variables in the Windows Control Panel so they stick around. So can you add

```
Alternatively, you can go to System Properties > Environment Variables and add to your User Variables there.
```

2022-10-12 08:59 UTC, tsa96 commented on _posts/guides/2022-10-11-guide_localization.md
> +On Linux:
Add something like

```
On Linux (it might help to put this in your .bashrc file or similar
```

2022-10-12 11:48 UTC, hexaflexahexagon commented
Closes https://github.com/momentum-mod/docs/issues/19 ? @Gocnak

2022-10-14 07:15 UTC, tsa96 approved these changes

2022-10-14 07:15 UTC, merged