the tricksurf doc
momentum-mod/docs pull request #306
Opened 2022-12-23 19:11 UTC by HitmanVRGTAG

2022-12-23 19:27 UTC, tsa96 requested changes
Addressed a bunch of things in my one review comment. Also, this file is in the wrong place, it should be nested in the _posts/guides/ stuff.

I suggest just copying your changes somewhere outside the repo (any text editor), then doing `git reset HEAD~1 --hard` to delete this commit. Then copy your changes into the correct file, address the stuff in the review, and this time when you push, use `git push --force`. This will get rid of the bad commit with the wrong file location.

2022-12-23 19:27 UTC, tsa96 commented on 2021-12-21-guide_gamemode-info-tricksurf.md
> +TrickSurf Began on https://zskyworld.com/, where a Surf/Combat Surf player known as Zee began posting his servers for tricksurfing. On zskyworld people posted tricks that they had made. Later on Tric
First off, let's keep terminology consistent, so "Tricksurf" not "TrickSurf".

Typo in "relese" an "there game" should be "their game".

Idk about saying "tricksurf began to die", seems better to be more specific that Zee's shut down. I believe that let to Tricksurf being dead for about a year, but there's `trick.surf` now. Honestly I think giving that a shoutout here would be fine. But could finish with something like " - despite that, Tricksurf remains a highly underrated mode that we hope sees more attention once added to Momentum."

Also feels like we're glossing over the history of Zee's a bit, maybe worth asking in the #general-tricksurf channel for some dates of when Zee's started and was most popular. "On zskyworld people posted tricks that they had made" reads a bit strangely - how exactly did people submit tricks, explain a little more about the system etc. Again, can always ask in the Discord, bunch of big tricksurf fans in there.

2023-01-12 00:45 UTC, hexaflexahexagon commented
@HitmanVRGTAG Any update on addressing the above PR review?

2023-05-06 18:02 UTC, tsa96 commented
Closing due to inactivity.

2023-05-06 18:02 UTC, closed without merging