Add information on ammo, weapons, and powerups.
momentum-mod/docs pull request #311
Opened 2023-04-27 04:08 UTC by chovelyoukai

Adds information for entities `momentum_powerup_damage_boost`, `momentum_powerup_haste`, `momentum_weapon_spawner`, `momentum_pickup_ammo`, cvar `mom_df_autoswitch`, and the various associated player inputs.

2023-04-28 01:44 UTC, EMERALD0874 requested changes

2023-04-28 01:44 UTC, EMERALD0874 commented on _posts/convars/2023-04-26-mom_df_autoswitch.md
> +Controlls switching behavior on weapon pickup. The default value of 1 causes autoswitch to happen on every weapon pickup. 0 disables autoswitch, and 2 only switches if the player gets a weapon that w
Should be "Controls"

2023-06-03 17:52 UTC, chovelyoukai commented
Updated to latest docs repo.

2023-06-03 18:09 UTC, Gocnak approved these changes

2023-06-03 18:31 UTC, merged