Fixed strange code block in parallax_corrected_cubemaps
momentum-mod/docs pull request #340
Opened 2024-12-06 15:23 UTC by PossiblePanda

fixed the documentation for parallax_corrected_cubemaps showing a code block of HTML

2024-12-06 15:27 UTC, PossiblePanda commented
![firefox_2KL47QRbNC](https://github.com/user-attachments/assets/67d06ad9-5cb6-4a96-ab06-e131d017a17c)
this is what it looked like before

2024-12-06 17:45 UTC, tsa96 requested changes
Not sure why this file contains any HTML in the first place -- looks like something didn't get updated when migration to Hugo.

It should be possible to get rid of all the HTML, and wrap the section in `{{< hint warning >}}` (Hugo shortcode)

2024-12-06 18:39 UTC, PossiblePanda commented
> {{< hint warning >}}

What do you mean by just deleting it? is that part of the docs not needed?

2024-12-07 11:24 UTC, tsa96 commented
Try changing
```
<div class="notice--warning">
        There are some important things to take note of:
        <br><br>
		<li>The <code>parallax_obb</code> entity must be a single box brush.</li>
		<li>The Parallax-Corrected cubemap is still built the same way regular cubemaps are.</li>
		<p>
		This means that you may have distortion in the reflections depending on where you place the <code>env_cubemap</code> and the shape of the <code>parallax_obb</code> brush.
		</p> <br>
		<p>
		This example has a wide room with a low ceiling as well as the cubemap entity not quite in the centre:
		</p>
		<img src="/images/cubemap_guide/cube_4.jpg" alt="Distortion example"> <br>
    	<p>
    	Parallax-Corrected cubemaps work best in box-shaped rooms and areas, the closer to a cube shape your <code>parallax_obb</code> is, the less obvious distortion that you will likely get.
    	</p> <br>
    	You should place the <code>env_cubemap</code> in the centre of the <code>parallax_obb</code> brush instead of at head height.

</div>
```
to 
```md
{{< hint warning >}}
There are some important things to take note of:
- The `parallax_obb` entity must be a single box brush.
- The Parallax-Corrected cubemap is still built the same way regular cubemaps are.

This means that you may have distortion in the reflections depending on where you place the `env_cubemap` and the shape of the `parallax_obb` brush.

This example has a wide room with a low ceiling as well as the cubemap entity not quite in the centre:

<img src="/images/cubemap_guide/cube_4.jpg" alt="Distortion example">

Parallax-Corrected cubemaps work best in box-shaped rooms and areas, the closer to a cube shape your `parallax_obb` is, the less obvious distortion that you will likely get.

You should place the `env_cubemap` in the centre of the `parallax_obb` brush instead of at head height.
{{ /hint }}

```

2024-12-07 12:50 UTC, PossiblePanda commented
> Try changing
> ```
> <div class="notice--warning">
>         There are some important things to take note of:
>         <br><br>
> 		<li>The <code>parallax_obb</code> entity must be a single box brush.</li>
> 		<li>The Parallax-Corrected cubemap is still built the same way regular cubemaps are.</li>
> 		<p>
> 		This means that you may have distortion in the reflections depending on where you place the <code>env_cubemap</code> and the shape of the <code>parallax_obb</code> brush.
> 		</p> <br>
> 		<p>
> 		This example has a wide room with a low ceiling as well as the cubemap entity not quite in the centre:
> 		</p>
> 		<img src="/images/cubemap_guide/cube_4.jpg" alt="Distortion example"> <br>
>     	<p>
>     	Parallax-Corrected cubemaps work best in box-shaped rooms and areas, the closer to a cube shape your <code>parallax_obb</code> is, the less obvious distortion that you will likely get.
>     	</p> <br>
>     	You should place the <code>env_cubemap</code> in the centre of the <code>parallax_obb</code> brush instead of at head height.
> 
> </div>
> ```
> to 
> ```md
> {{< hint warning >}}
> There are some important things to take note of:
> - The `parallax_obb` entity must be a single box brush.
> - The Parallax-Corrected cubemap is still built the same way regular cubemaps are.
> 
> This means that you may have distortion in the reflections depending on where you place the `env_cubemap` and the shape of the `parallax_obb` brush.
> 
> This example has a wide room with a low ceiling as well as the cubemap entity not quite in the centre:
> 
> <img src="/images/cubemap_guide/cube_4.jpg" alt="Distortion example">
> 
> Parallax-Corrected cubemaps work best in box-shaped rooms and areas, the closer to a cube shape your `parallax_obb` is, the less obvious distortion that you will likely get.
> 
> You should place the `env_cubemap` in the centre of the `parallax_obb` brush instead of at head height.
> {{ /hint }}
> 
> ```

Ahh gotcha, I didn't see the notice--warning div so I wasn't sure what you wanted me to wrap that with. I'll add these changes in a few minutes

2024-12-07 16:02 UTC, PossiblePanda commented
Added the changes.

2024-12-07 16:55 UTC, tsa96 approved these changes

2024-12-07 17:04 UTC, merged